<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0-preview.7.24405.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0-preview.7.24405.3" />
      <PackageReference Include="RestSharp" Version="112.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthData\AuthData.csproj" />
      <ProjectReference Include="..\ProductsRepo\ProductsRepo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\Views\Shared\_Layout.en-US.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.en-US.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Index.en-US.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.en-US.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Index.ru-RU.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.ru-RU.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Shared\_Layout.ru-RU.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.ru-RU.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Privacy.ru-RU.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Privacy.ru-RU.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Views\Home\Privacy.en-US.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Privacy.en-US.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Views\Shared\_Layout.en-US.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.en-US.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Home\Index.en-US.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.en-US.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Home\Index.ru-RU.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.ru-RU.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Shared\_Layout.ru-RU.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.ru-RU.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Home\Privacy.ru-RU.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Privacy.ru-RU.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\Views\Home\Privacy.en-US.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Privacy.en-US.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
