networks:
  my_bridge_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./Front/
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - my_bridge_network
    depends_on:
      - backend
  

  backend:
    build:
      context: ./Back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_bridge_network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    ports:
      - "1433:1433"
    networks:
      - my_bridge_network
    environment:
      SA_PASSWORD: "Elvin123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: