global:
  scrape_interval: 15s # Интервал между запросами метрик
  evaluation_interval: 15s # Интервал для вычисления правил оповещения
  scrape_timeout: 10s # Таймаут для запросов метрик

# Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "localhost:9093" # Адрес Alertmanager

# Список таргетов для мониторинга
scrape_configs:
  # Мониторинг самого Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9091"]
        labels:
          environment: "local"
          service: "prometheus"
  - job_name: "aspnet_webapi"
    static_configs:
      - targets: ["localhost:8080"]
        labels:
          environment: "development"
          service: "aspnet-webapi"
  