apiVersion: v1
kind: Service
metadata:
  name: kube-test-service
spec:
  type: NodePort
  selector:
    app: kube-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
