apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: microservices
type: Opaque
data:
  ConnectionStrings__DefaultMacAuth: RGF0YSBTb3VyY2U9bG9jYWxob3N0OyBJbml0aWFsIENhdGFsb2c9QXV0aF84OyBVc2VyIElkPXNhOyBQYXNzd29yZD1FbHZpbjEyMzsgVHJ1c3QgU2VydmVyIENlcnRpZmljYXRlPVRydWU7
  Jwt__Key: ZjQzOWE4ODgzMzQ3YzhiOTU4OWMzMWM2ZDdjOWRkYTBiYjFhYjAzZg==
  Jwt__Issuer: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  Jwt__Audience: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  EmailJwt__Key: UTBkRGFXaE1ZVFJZT0NzM2R6SnRVVkJEZW5rM05IWkJaMjQxUlV4TGMzTmhiMHhvUmxVeFNHVldRVDA9
  EmailJwt__Issuer: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  EmailJwt__Audience: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  Email__Host: c210cC5nbWFpbC5jb20=
  Email__Port: NTg3
  Email__EnableSsl: dHJ1ZQ==
  Email__Username: cHJvZmJhdDAxOEBnbWFpbC5jb20=
  Email__Password: emd4bWtodGdndGphZGRpZA==
  