<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\ProductData\ProductData.csproj" />
      <ProjectReference Include="..\ProductsRepo\ProductsRepo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.22.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    </ItemGroup>

</Project>
