apiVersion: v1
kind: Secret
metadata:
  name: communication-secrets
  namespace: microservices
type: Opaque
data:
  ConnectionStrings__CommunicationDb: RGF0YSBTb3VyY2U9bG9jYWxob3N0OyBJbml0aWFsIENhdGFsb2c9Q29tbXVuaWNhdGlvbkRiOyBVc2VyIElkPXNhOyBQYXNzd29yZD1FbHZpbjEyMzsgVHJ1c3QgU2VydmVyIENlcnRpZmljYXRlPVRydWU7
  Jwt__Key: ZjQzOWE4ODgzMzQ3YzhiOTU4OWMzMWM2ZDdjOWRkYTBiYjFhYjAzZg==
  Jwt__Issuer: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  Jwt__Audience: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  gRPC__UserService: aHR0cDovL2xvY2FsaG9zdDo1MDAx
