apiVersion: v1
kind: Secret
metadata:
  name: movie-secrets
  namespace: microservices
type: Opaque
data:
  ConnectionStrings__MoviesDb: RGF0YSBTb3VyY2U9bG9jYWxob3N0OyBJbml0aWFsIENhdGFsb2c9TW92aWVzRGI7IFVzZXIgSWQ9c2E7IFBhc3N3b3JkPUVsdmluMTIzOyBUcnVzdCBTZXJ2ZXIgQ2VydGlmaWNhdGU9VHJ1ZTs=
  Jwt__Key: ZjQzOWE4ODgzMzQ3YzhiOTU4OWMzMWM2ZDdjOWRkYTBiYjFhYjAzZg==
  Jwt__Issuer: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  Jwt__Audience: aHR0cDovL2xvY2FsaG9zdDo3Mjgx
  TmdbApi__Key: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKaGRXUWlPaUl5WVRjeFlXTXhOVGMzTnpka1pUTTNZekl4TlRGalkyUTNPVFF4WmpVMVlTSXNJbTVpWmlJNk1UWTVOemM0TkRZMk9TNHlNRGdzSW5OMVlpSTZJalkxTXpJeU16VmtPV0ZqTlRNMU1EZzNOelUyTUdFell5SXNJbk5qYjNCbGN5STZXeUpoY0dsZmNtVmhaQ0pkTENKMlpYSnphVzl1SWpveGZRLmhGUkFmWUlaM2M1ODliY1BPdzhnREdOX2ZQV1QxQlpuaW1qVXhsYllhM0k=